# Project 4 - Creditworthiness Prediction

### Description of Data Values

* Status of existing checking account
	* A11: ... < 0 EUR
	*  A12: 0 ≤ ... < 200 EUR
	*  A13: ... ≥ 200 EUR / salary assignments for at least 1 year
	* A14: no checking account
* Duration in month
* Credit history
	* A30: no credits taken/ all credits paid back duly
	* A31: all credits at this bank paid back duly
	* A32: existing credits paid back duly till now
	* A33: delay in paying off in the past
	* A34: critical account/ other credits existing (not at this bank)
* Purpose (incomplete)
	* A40: car (new)
	* A41: car (used)
	* A42: furniture/equipment
	* A43: radio/television
	* A44: domestic appliances
	* A45: repairs
	* A46: education
	* A47: (vacation - does not exist?)
	*  A48: retraining
	* A49: business
	*  A410: others
* Credit amount
* Savings account/bonds
	* A61: ... < 100 EUR
	*  A62: 100 ≤ ... < 500 EUR
	* A63: 500 ≤ ... < 1000 EUR
	*  A64: .. ≥ 1000 EUR
	* A65: unknown/ no savings account
* Present employment since (incomplete)
	* A71: unemployed
	* A72: ... < 1 year
	*  A73: 1 ≤ ... < 4 years
	*  A74: 4 ≤ ... < 7 years
	*  A75: .. ≥ 7 years
* Instalment rate in percentage of disposable income
* Personal status and sex
	* A91: male: divorced/separated
	* A92: female: divorced/separated/married
	*  A93: male: single
	*  A94: male: married/widowed
	* A95: female: single
* Other debtors / guarantors
	* A101: none
	*  A102: co-applicant
	*  A103: guarantor
* Present residence since
* Property
	* A121: real estate
	* A122: if not A121: building society savings agreement/ life insurance
	* A123: if not A121/A122: car or other, not in attribute  6
	*  A124: unknown / no property
* Age in years
* Other installment plans
	* A141: bank
	*  A142: stores
	*  A143: none
* Housing
	*  A151: rent
	*  A152: own
	*  A153: for free
* Number of existing credits at this bank
* Job (incomplete)
	* A171: unemployed/ unskilled - non-resident
	*  A172: unskilled - resident
	*  A173: skilled employee / official
	*  A174: management/ self-employed/
	*  A175: highly qualified employee/ officer
* Number of people being liable to provide maintenance for
* Telephone
	*  A191: none
	*  A192: yes, registered under the customers name
* Foreign worker (incomplete)
	* A201: yes
	* A202: no
* Creditworthy
	* 1: yes
	* 2: no

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
cols = ['Status of existing checking account', 'Duration in month', 'Credit history', 'Purpose (incomplete)', 
        'Credit amount', 'Savings account/bonds', 'Present employment since (incomplete)', 'Instalment rate in % of disposable income',
       'Personal status and sex', 'Other debtors / guarantors', 'Present residence since', 'Property', 'Age', 'Other installment plans', 
       'Housing', 'Number of existing credits at this bank', 'Job (incomplete)', 'Number of people being liable to provide maintenance for',
       'Telephone', 'Foreign worker (incomplete)', 'Creditworthy']

In [3]:
df = pd.read_csv('kredit.dat', sep='\t', header=None, names=cols, na_values="?" )

In [4]:
df

,Status of existing checking account,Duration in month,Credit history,Purpose (incomplete),Credit amount,Savings account/bonds,Present employment since (incomplete),Instalment rate in % of disposable income,Personal status and sex,Other debtors / guarantors,...,Property,Age,Other installment plans,Housing,Number of existing credits at this bank,Job (incomplete),Number of people being liable to provide maintenance for,Telephone,Foreign worker (incomplete),Creditworthy
0,A14,36,A32,NaN,2299,A63,NaN,4,A93,A101,...,A123,39,A143,A152,1,A173,1,A191,NaN,1
1,A12,18,A32,A46,1239,A65,A73,4,A93,A101,...,A124,61,A143,A153,1,NaN,1,A191,A201,1
2,A13,24,A32,A40,947,A61,A74,4,A93,A101,...,A124,38,A141,A153,1,NaN,2,A191,NaN,2
3,A14,15,A33,A43,1478,A61,A73,4,A94,A101,...,A121,33,A141,A152,2,A173,1,A191,A201,1
4,A14,24,A32,A40,1525,A64,A74,4,A92,A101,...,A123,34,A143,A152,1,A173,2,A192,A201,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,A14,21,A32,A49,1572,A64,A75,4,A92,A101,...,A121,36,A141,A152,1,NaN,1,A191,NaN,1
996,A11,6,A31,A46,1198,A61,A75,4,A92,A101,...,A124,35,A143,A153,1,A173,1,A191,A201,2
997,A12,12,A32,A40,685,A61,A74,2,A94,A101,...,A123,25,A141,A152,1,NaN,1,A191,A201,2
998,A11,24,A32,A40,1381,A65,NaN,4,A92,A101,...,A122,35,A143,A152,1,A173,1,A191,A201,2
999,A12,12,A32,A40,1223,A61,A75,1,A91,A101,...,A121,46,A143,A151,2,A173,1,A191,A201,2

In [5]:
df.shape

(1000, 21)

In [6]:
df.dtypes

Status of existing checking account                         object
Duration in month                                            int64
Credit history                                              object
Purpose (incomplete)                                        object
Credit amount                                                int64
Savings account/bonds                                       object
Present employment since (incomplete)                       object
Instalment rate in % of disposable income                    int64
Personal status and sex                                     object
Other debtors / guarantors                                  object
Present residence since                                      int64
Property                                                    object
Age                                                          int64
Other installment plans                                     object
Housing                                                     object
Number of existing credits at this bank                      int64
Job (incomplete)                                            object
Number of people being liable to provide maintenance for     int64
Telephone                                                   object
Foreign worker (incomplete)                                 object
Creditworthy                                                 int64
dtype: object

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   Status of existing checking account                       1000 non-null   object
 1   Duration in month                                         1000 non-null   int64
 2   Credit history                                            1000 non-null   object
 3   Purpose (incomplete)                                      827 non-null    object
 4   Credit amount                                             1000 non-null   int64
 5   Savings account/bonds                                     1000 non-null   object
 6   Present employment since (incomplete)                     504 non-null    object
 7   Instalment rate in % of disposable income                 1000 non-null   int64
 8   Personal status and sex                                   1000 non-null   object
 9   Other debtors / guarantors                                1000 non-null   object
 10  Present residence since                                   1000 non-null   int64
 11  Property                                                  1000 non-null   object
 12  Age                                                       1000 non-null   int64
 13  Other installment plans                                   1000 non-null   object
 14  Housing                                                   1000 non-null   object
 15  Number of existing credits at this bank                   1000 non-null   int64
 16  Job (incomplete)                                          768 non-null    object
 17  Number of people being liable to provide maintenance for  1000 non-null   int64
 18  Telephone                                                 1000 non-null   object
 19  Foreign worker (incomplete)                               640 non-null    object
 20  Creditworthy                                              1000 non-null   int64
dtypes: int64(8), object(13)
memory usage: 164.2+ KB

In [6]:
# Get the data statistics

df.describe()

,Duration in month,Credit amount,Instalment rate in % of disposable income,Present residence since,Age,Number of existing credits at this bank,Number of people being liable to provide maintenance for,Creditworthy
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,20.903000,3271.258000,2.973000,2.845000,35.546000,1.407000,1.155000,1.300000
std,12.058814,2822.736876,1.118715,1.103718,11.375469,0.577654,0.362086,0.458487
min,4.000000,250.000000,1.000000,1.000000,19.000000,1.000000,1.000000,1.000000
25%,12.000000,1365.500000,2.000000,2.000000,27.000000,1.000000,1.000000,1.000000
50%,18.000000,2319.500000,3.000000,3.000000,33.000000,1.000000,1.000000,1.000000
75%,24.000000,3972.250000,4.000000,4.000000,42.000000,2.000000,1.000000,2.000000
max,72.000000,18424.000000,4.000000,4.000000,75.000000,4.000000,2.000000,2.000000

In [ ]:
# df['Creditworthy'] = df["Creditworthy"].astype('category')

In [ ]:
# Separate df into the X and pop out 'Creditworthy' into y since it's the target we want to predict

X = df.copy()

# Change the last column to boolean. Convert 1 - Creditworhty and 2 - Not creditworthy to True and False respectively

# X["Creditworthy"] = np.where(X["Creditworthy"] == 1, True, False)
y = X.pop('Creditworthy')

In [5]:
df.dtypes

Status of existing checking account                         object
Duration in month                                            int64
Credit history                                              object
Purpose (incomplete)                                        object
Credit amount                                                int64
Savings account/bonds                                       object
Present employment since (incomplete)                       object
Instalment rate in % of disposable income                    int64
Personal status and sex                                     object
Other debtors / guarantors                                  object
Present residence since                                      int64
Property                                                    object
Age                                                          int64
Other installment plans                                     object
Housing                                                     object
Number of existing credits at this bank                      int64
Job (incomplete)                                            object
Number of people being liable to provide maintenance for     int64
Telephone                                                   object
Foreign worker (incomplete)                                 object
Creditworthy                                                 int64
dtype: object

In [ ]:
# Function to calculate missing values by column
def missing_values_table(df):
        # Total missing values
        mis_val = df.isnull().sum()
        
        # Percentage of missing values
        mis_val_percent = 100 * df.isnull().sum() / len(df)
        
        # Make a table with the results
        mis_val_table = pd.concat([mis_val, mis_val_percent], axis=1)
        
        # Rename the columns
        mis_val_table_ren_columns = mis_val_table.rename(
        columns = {0 : 'Missing Values', 1 : '% of Total Values'})
        
        # Sort the table by percentage of missing descending
        mis_val_table_ren_columns = mis_val_table_ren_columns[
            mis_val_table_ren_columns.iloc[:,1] != 0].sort_values(
        '% of Total Values', ascending=False).round(1)
        
        # Print some summary information
        print ("This dataframe has " + str(df.shape[1]) + " columns.\n"      
            "There are " + str(mis_val_table_ren_columns.shape[0]) +
              " columns that have missing values.")
        
        # Return the dataframe with missing information
        return mis_val_table_ren_columns

In [ ]:
missing_values_table(df)

In [ ]:
# Histogram of the creditworthiness

plt.style.use('seaborn')
plt.hist(df['Creditworthy'])
plt.xlabel('Creditworthy') 
plt.ylabel('Number of Clients');
plt.title('Creditworthiness Distribution')

In [ ]:
# # Correlations between Features and Target

# Find all correlations and sort 
correlations_df = df.corrwith(df['Creditworthy']).sort_values()

# Print the correlations
print(correlations_df, '\n')

In [8]:
df2 = df.copy()

In [ ]:
# obj_df = df2.select_dtypes(include=['object']).copy()

In [ ]:
# obj_df.columns.tolist()

In [ ]:
# for col in obj_df.columns.tolist():
#     df2[col] = df2[col].astype('category')

In [ ]:
# Drop Present employment... and Foreign worker columns since a large part the data is empty

# df2 = df2.drop(columns= ['Present employment since (incomplete)', 'Foreign worker (incomplete)'])

In [ ]:
missing_values_table(df2)

In [ ]:
sns.pairplot(df2, hue='Creditworthy')

In [ ]:
# df2['Job (incomplete)'] = df2['Job (incomplete)'].fillna("Unknown")
# df2['Purpose (incomplete)'] = df2['Purpose (incomplete)'].fillna("Unknown")

In [ ]:
df2

In [ ]:
# from sklearn.preprocessing import OneHotEncoder

# enc = OneHotEncoder(sparse=False)
# hot = enc.fit_transform(df2)

In [ ]:
# df2 = pd.get_dummies(df2)

In [14]:
df2 = df2.dropna(axis=1)

In [15]:
df2.shape

(1000, 17)

In [ ]:
correlations_df2 = df2.corrwith(df['Creditworthy']).sort_values()

# Print the correlations
correlations_df2

In [ ]:
df2.columns

In [ ]:
df2.isna()

In [ ]:
# from sklearn.preprocessing import MinMaxScaler

# scaler = MinMaxScaler()
# scaled_df2 = pd.DataFrame(scaler.fit_transform(df2), columns = df2.columns)
# scaled_df2

In [ ]:
df2.isna().sum()

In [ ]:
# from sklearn.impute import KNNImputer

# imputer = KNNImputer(n_neighbors=5)
# imputed_df2 = pd.DataFrame(imputer.fit_transform(df2),columns = scaled_df2.columns)

In [ ]:
# # # Feature Engineering and Selection

def remove_collinear_features(X, threshold):
    '''
    Objective:
        Remove collinear features in a dataframe with a correlation coefficient
        greater than the threshold. Removing collinear features can help a model
        to generalize and improves the interpretability of the model.
        
    Inputs: 
        threshold: any features with correlations greater than this value are removed
    
    Output: 
        dataframe that contains only the non-highly-collinear features
    '''

    
    # Calculate the correlation matrix
    corr_matrix = X.corr()
    iters = range(len(corr_matrix.columns) - 1)
    drop_cols = []

    # Iterate through the correlation matrix and compare correlations
    for i in iters:
        for j in range(i):
            item = corr_matrix.iloc[j:(j+1), (i+1):(i+2)]
            col = item.columns
            row = item.index
            val = abs(item.values)
            
            # If correlation exceeds the threshold
            if val >= threshold:
                # Print the correlated features and the correlation value
                # print(col.values[0], "|", row.values[0], "|", round(val[0][0], 2))
                drop_cols.append(col.values[0])

    # Drop one of each pair of correlated columns
    drops = set(drop_cols)
    X = X.drop(columns = drops)
    
               
    return X

In [ ]:
X = remove_collinear_features(X, 0.6)

In [21]:
df2 = pd.get_dummies(df2, dummy_na=True)

In [ ]:
# Separate df into the X and pop out 'Creditworthy' into y since it's the target we want to predict

X = onehot_df2.copy()

# Change the last column to boolean. Convert 1 - Creditworhty and 2 - Not creditworthy to True and False respectively

X["Creditworthy"] = np.where(X["Creditworthy"] == 1, True, False)
y = X.pop('Creditworthy')

In [17]:
# Splitting data into training and testing
from sklearn.model_selection import train_test_split

# Split into 80% training and 20% testing set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 101)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(800, 16)
(200, 16)
(800,)
(200,)

In [18]:

# I will compare five different machine learning Cassification models:

# 1 - Logistic Regression
# 2 - K-Nearest Neighbors Classification
# 3 - Suport Vector Machine
# 4 - Naive Bayes
# 5 - Random Forest Classification

# Function to calculate mean absolute error
def cross_val(X_train, y_train, model):
    # Applying k-Fold Cross Validation
    
    from sklearn.model_selection import cross_val_score
    
    accuracies = cross_val_score(estimator = model, X = X_train, y = y_train)
    
    return accuracies.mean()

# Takes in a model, trains the model, and evaluates the model on the test set
def fit_and_evaluate(model):
    
    # Train the model
    model.fit(X_train, y_train)
    
    # Make predictions and evalute
    model_pred = model.predict(X_test)
    model_cross = cross_val(X_test, y_test, model)
    
    # Return the performance metric
    return model_cross

In [19]:
from sklearn.naive_bayes import GaussianNB
naive = GaussianNB()
naive_cross = fit_and_evaluate(naive)

print('Naive Bayes Performance on the test set: Cross Validation Score = %0.4f' % naive_cross)

ValueError: could not convert string to float: 'A11'

In [20]:
from sklearn.ensemble import RandomForestClassifier
random = RandomForestClassifier(n_estimators = 10, criterion = 'entropy')
random_cross = fit_and_evaluate(random)

print('Random Forest Performance on the test set: Cross Validation Score = %0.4f' % random_cross)

ValueError: could not convert string to float: 'A11'

In [ ]:
from xgboost import XGBClassifier
gb = XGBClassifier()
gb_cross = fit_and_evaluate(gb)

print('Gradiente Boosting Classification Performance on the test set: Cross Validation Score = %0.4f' % gb_cross)